### ISSUE TITLE
கேள்வி -- சிறப்பு சொற்கள் பட்டியல் ?

### ISSUE THREAD

**Issue by mramanathan** [Ezhil-Language-Foundation/Ezhil-Lang#185]
Python-இல் உள்ளது போல், சிறப்புச் சொற்களை பட்டியலிட வசதி உள்ளதா ?

அதாவது இவ்வாறு (Python-இல் IDLE interface-இல் இந்த வசதி உள்ளது) :

`import keyword`
`keyword.kwlist`
['False', 'None', 'True', 'and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

**Comment by arcturusannamalai** [comment]
வணக்கம் திரு இராமநாதன். இந்த வேலையை சிறிது காலம் முன்னேற செய்தேன்.
இங்கு பார்க்கவும் : https://github.com/Ezhil-Language-Foundation/Ezhil-Lang/commit/29df7b7681afd1fd3df90ea27d7ea75b54a6221f

உருவாக்கும் (dev) கிளையில் இருந்து எழில் இடைமுகத்தில் இவ்வாறு, கொடுத்தால் குறிச்சொற்களை பெறலாம் 
```
>> குறிசொற்கள்()
 ```

உங்களுக்கு தீபாவளி பண்டிகை வாழ்த்துக்கள்!

**Comment by mramanathan** [comment]
@arcturusannamalai மிக்க நன்றி. 

உங்களுக்கும் எனது தீபாவளி பண்டிகை நல்வாழ்த்துக்கள்!!!

பி.கு
இடைமுகத்தில் தமிழ் எழுத்துருக்கள் ஒன்றின் மேல் ஒன்றாக (overwritten, x-term-இல்) காண்கின்றேன். அடுத்து இதை சரிசெய்யவேண்டும்.

**Comment by arcturusannamalai** [comment]
இதனை gnome அல்லது KDE திட்டத்தில் கோளாறு தகவல் சொன்னால் அவர்கள் சரி செய்வது தான் முறையானது.
