### ISSUE TITLE
How to output by பதிப்பி without space.

### ISSUE THREAD

**Issue by skytomo221** [Ezhil-Language-Foundation/Ezhil-Lang#208]
```n
x = "out"
y = "put"
பதிப்பி x, y
```

Output:
```
out put
```

I want to output "`output`" but not "`out put`".
How do I do this?

**Comment by arcturusannamalai** [comment]
நீங்கள் இதனை பயன்படுத்தி பார்க்கலாம்:
̀̀̀̀̀̀̀̀
`பதிப்பி x+y
`
அல்லது
`
அச்சிடு("%s%s",x,y)
`
என்றும் பயன்படுத்திப்பார்க்கலாம்

**Comment by skytomo221** [comment]
நன்றி
