### ISSUE TITLE
ImportError: cannot import name 'clock' from 'time' (unknown location)

### ISSUE THREAD

**Issue by raxod502** [Ezhil-Language-Foundation/Ezhil-Lang#210]
Ezhil no longer starts up successfully with Python 3.8:

```
% ezhili
Traceback (most recent call last):
  File "/opt/ezhil/bin/ezhili", line 5, in <module>
    from ezhil.ezhil import main
  File "/opt/ezhil/lib/python3.8/site-packages/ezhil/__init__.py", line 16, in <module>
    from .ezhil import ezhil_file_REPL, main, ezhil_timeout_exec, ezhil_eval
  File "/opt/ezhil/lib/python3.8/site-packages/ezhil/ezhil.py", line 36, in <module>
    from time import sleep,clock,time
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

The function `time.clock` has been removed in Python 3.8, after being deprecated in Python 3.3. Reference: https://github.com/PyTables/PyTables/issues/744

**Comment by arcturusannamalai** [comment]
Thanks for bug report; Could you submit a PR? @raxod502

**Comment by raxod502** [comment]
Ah, I see, this was already fixed in https://github.com/ezhil-language-foundation/Ezhil-Lang/commit/cd3b69cb1da91f1b2d4cf63a36229ea1c2abb4af; we just need a new release since the last one on PyPI is 0.99 from Aug 2017.

**Comment by arcturusannamalai** [comment]
Okay will do by end of week. Thanks.

**Comment by arcturusannamalai** [comment]
Resolved by
```
python3 -m pip install ezhil==1.0.rc0
```
